[package]
name = "final_project"
version = "0.1.0"
edition = "2021"

[dependencies]
spider = "1.28"
tokio = { version = "1", features = ["full"] }
scraper = "0.13"
cursive = { git = "https://github.com/gyscos/cursive" }
url = "2.3.1"
cursive-async-view = "^0"